# Generated by Django 4.1.13 on 2024-03-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, null=True, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('designer', models.CharField(max_length=255)),
                ('old_price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('is_active', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('categories', models.ManyToManyField(related_name='mobiles', to='category.category')),
            ],
            options={
                'verbose_name_plural': 'Mobiles',
                'db_table': 'mobile',
            },
        ),
    ]
